before_commands:
    - "composer install --no-dev --prefer-source"
filter:
    paths:
        - 'src/*'
    excluded_paths:
        - bin
        - vendor
checks:
    php:
        code_rating: true
        duplication: true
tools:
    php_code_coverage:
        enabled: true
    php_cpd:
        enabled: true
        excluded_dirs:
            - bin
            - vendor
    php_loc:
        enabled: true
        excluded_dirs:
            - bin
            - vendor
    php_mess_detector:
        enabled: false
    php_analyzer:
        enabled: true
    sensiolabs_security_checker: true
#     php_code_sniffer:
#         enabled: true
#         config:
#             standard: Sutra
