before_commands:
    - "composer install --no-dev --prefer-source"
tools:
    php_code_coverage:
        enabled: true
    php_cpd:
        enabled: true
        excluded_dirs:
            - bin
            - vendor
    php_loc:
        enabled: true
        excluded_dirs:
            - bin
            - vendor
    php_mess_detector:
        enabled: false
        filter:
            paths:
                - 'src/*'
    php_analyzer:
        enabled: true
        filter:
            paths:
                - 'src/*'
    sensiolabs_security_checker: true
#     php_code_sniffer:
#         enabled: true
#         config:
#             standard: Sutra
