filter:
    paths:
        - src/*
    excluded_paths:
        - bin/*
        - vendor/*
tools:
    php_code_coverage:
        test_command: bin/phpunit
#     php_code_sniffer:
#         enabled: true
#         command: bin/phpcs
#         config:
#             standard: Sutra
#     php_cpd:
#         enabled: true
#     php_loc:
#         enabled: true
#         excluded_dirs:
#             - bin
#             - classes
#             - vendor
#     php_mess_detector:
#         enabled: true
#     php_analyzer:
#         enabled: true
before_commands:
    - "composer install --prefer-source"
